// User roles
export enum UserRole {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  COMPANY = 'COMPANY',
  EMPLOYEE = 'EMPLOYEE'
}

// Employee subroles
export enum EmployeeSubrole {
  MANAGER = 'MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  OPERATOR = 'OPERATOR',
  GUARD = 'GUARD'
}

// Session statuses
export enum SessionStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

// Seal statuses
export enum SealStatus {
  PENDING = 'PENDING',
  APPLIED = 'APPLIED',
  REMOVED = 'REMOVED',
  DAMAGED = 'DAMAGED'
}

// Vehicle statuses
export enum VehicleStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

// Activity log actions
export enum ActivityAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  CREATE_SESSION = 'CREATE_SESSION',
  UPDATE_SESSION = 'UPDATE_SESSION',
  COMPLETE_SESSION = 'COMPLETE_SESSION',
  CANCEL_SESSION = 'CANCEL_SESSION',
  ADD_SEAL = 'ADD_SEAL',
  REMOVE_SEAL = 'REMOVE_SEAL',
  ADD_COMMENT = 'ADD_COMMENT',
  GENERATE_REPORT = 'GENERATE_REPORT',
  VERIFY_SEAL = 'VERIFY_SEAL',
  CREATE_COMPANY = 'CREATE_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',
  TRANSFER_COINS = 'TRANSFER_COINS',
  ALLOCATE_COINS = 'ALLOCATE_COINS',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW'
}

// Transaction reasons
export enum TransactionReason {
  SESSION_CREATION = 'SESSION_CREATION',
  ADMIN_ALLOCATION = 'ADMIN_ALLOCATION',
  SUPERADMIN_ALLOCATION = 'SUPERADMIN_ALLOCATION',
  REFUND = 'REFUND'
}

// Session types
export enum SessionType {
  LOADING = 'LOADING',
  UNLOADING = 'UNLOADING',
  INSPECTION = 'INSPECTION'
}

// Permission types
export enum Permission {
  CREATE_SESSION = 'CREATE_SESSION',
  MANAGE_SESSIONS = 'MANAGE_SESSIONS',
  MANAGE_EMPLOYEES = 'MANAGE_EMPLOYEES',
  GENERATE_REPORTS = 'GENERATE_REPORTS',
  VERIFY_SEALS = 'VERIFY_SEALS',
  MANAGE_COINS = 'MANAGE_COINS'
} 